site_name: 王鹤的小站
site_language: zh
repo_name: mkdocs
repo_url: https://github.com/wisehai/mkdocs

copyright: Copyright &copy; 2024-present <a href="https://github.com/wisehai/" target="_blank" rel="noopener noreferrer">wisehai</a>

theme:
  name: material
  favicon: images/favicon.ico

  language: zh
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/wisehai
    - icon: fontawesome/brands/zhihu
    #  link: https://www.zhihu.com/people/wisehai
    - icon: fontawesome/brands/bilibili
    #  link: https://space.bilibili.com/10162516

    #- icon: fontawesome/brands/openai

plugins:
  - search:
      separator: '[\s\u200b\-]'

nav:
  - 主页: index.md
  - 'AI站': 'https://ai.wisehai.com/'
  - 日志: 
    - 2024年5月: 2024-05.md
  - 自然语言: 
    - 英语: english.md
    - 中文写作: nav2.md
  - 编程语言: 
    - web前端: 
      - html: web.md
      - css: web2.md
      - javascript: web3.md
    - Python: python.md
  
  
